# Generated by Django 6.0.6 on 2026-07-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=100000)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='lostitems/')),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
