# Generated by Django 6.0.6 on 2026-07-05 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_item_delete_todoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ItemImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Description',
        ),
        migrations.AddField(
            model_name='item',
            name='catagories',
            field=models.CharField(choices=[('Dev', 'DEVICES (Phone, Laptop, Tablet, Headphones)'), ('Doc', 'DOCUMENTS (IDs, Student Cards, Passports, Notebooks)'), ('Acc', 'ACCESSORIES (Keys, Wallets, Bags, Umbrellas)'), ('Clo', 'CLOTHING (Jackets, Hats, Gloves, Footwear)'), ('Sta', 'STATIONERY (Pens, Calculators, Art Supplies)'), ('Oth', 'OTHER (Water Bottles, Sports Gear, Miscellaneous)')], default='Oth', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('L', 'LOST ITEM'), ('F', 'FOUND ITEM'), ('C', 'CLAIMED')], default='L', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
